### PR TITLE
Add `DataContainerConfigOptionToParameterRector`

### PR DESCRIPTION
**Pull request by zoglo**
### Description

- Implements #3

_**Old:**_
```php
'screenshot' => [
    'exclude' => true,
    'inputType' => 'fileTree',
    'eval' => ['fieldType'=>'radio', 'filesOnly'=>true, 'isGallery'=>true, 'extensions'=>Contao\Config::get('validImageTypes')],
    'sql' => "binary(16) NULL"
],
```

**_New:_**
```php
'screenshot' => [
    'exclude' => true,
    'inputType' => 'fileTree',
    'eval' => ['fieldType'=>'radio', 'filesOnly'=>true, 'isGallery'=>true, 'extensions'=>'%contao.image.valid_extensions%'],
    'sql' => "binary(16) NULL"
],
```

#### Test
image

### CODE REVIEW

**Comment by aschempp** [comment]
I'm not sure this is correct. We can only replace the config option with a parameter where it is expected to work, e.g. in the DCA config. If my custom code retrieves this value, we cannot replace this with a string, it would break everything?

**Comment by zoglo** [comment]
Same as https://github.com/contao/contao-rector/pull/8#issuecomment-2102803213 - Might need to limit it to specific arrays and entry types (array keys) to change the value.

**Comment by zoglo** [comment]
@aschempp This one is even more specific now and checks if it's in an array with key an `eval`, then checks the `extensions` and whether the static call is the `Contao\Config::class` with method get to replace it

image

Could do the same for #6 if we want it even more specific as well 🤔

**Comment by zoglo** [comment]
Will be merged with #6

**Pull request closed without merging**
